### ISSUE TITLE
Chartist is not defined

### ISSUE THREAD

**Issue by Dennisoost** [Yopadd/chartist-vuejs#2]
Getting the chartist is not defined error

Main.js:
```
import Chartist from 'chartist-vuejs'
Vue.use(Chartist)

```

Also tried it with 
`Vue.use(require('chartist-vuejs))`

my vue component: 
```
<template>
  <chartist
    id-chart="ct-chart"
    ratio="ct-major-second"
    type="Line"
    :data="chartData"
    :options="chartOptions" >
</chartist>
</template>
<script>
export default {
  components: {
  },
  data: function () {
    return {
      chartData: {
        labels: ['mo', 'tu', 'we'],
        series: [[1, 2, 3], [1, 2, 3]]
      },
      chartOptions: {
        lineSmooth: false
      }
    }
  }
}
</script>
```

Anything i'm missing?

**Comment by Dennisoost** [comment]
Apparently i wasn't importing chartist (not the vue variant).
Added: https://cdnjs.cloudflare.com/ajax/libs/chartist/0.9.7/chartist.min.js
and: https://cdnjs.cloudflare.com/ajax/libs/chartist/0.9.7/chartist.min.css

to my index.html and works fine now ;)

(had issues with npm install chartist and importing it with webpack, that's why i use cdn)

**Comment by Yopadd** [comment]
Hi, 
Yes you must add Chartist.js and Chartist.css for the plugin works correctly.
I will add this note in the readme.

**Comment by kartsims** [comment]
Stumbled across the same problem, it is nt yet in the README ;-)

**Comment by kartsims** [comment]
Oh sorry I didn't see that the issue was closed only yesterday ! So much pressure... haha
